language: python
python:
    - 2.6
    - 2.7
install:
    - virtualenv env
    - env/bin/pip install -U setuptools distribute
    - env/bin/python bootstrap.py
    - bin/buildout
script:
    - bin/test
notifications:
    email: false
